
CREATE TABLE difficulty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(255) UNIQUE NOT NULL -- 'beginner', 'intermediate', 'expert'
);


CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    difficulty_id BIGINT, -- The foreign key lives here!

    CONSTRAINT fk_user_difficulty FOREIGN KEY (difficulty_id) REFERENCES difficulty(id)
);


CREATE TABLE code_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty_id BIGINT NOT NULL,
    code TEXT NOT NULL,
    answer TEXT NOT NULL,

    CONSTRAINT fk_problem_difficulty FOREIGN KEY (difficulty_id) REFERENCES difficulty(id)
);

INSERT INTO difficulty (level) VALUES ('beginner');
INSERT INTO difficulty (level) VALUES ('intermediate');
INSERT INTO difficulty (level) VALUES ('expert');